# Assignment 3

# Question 1

In [3]:
import numpy as np
print(np.arange(2,50,3))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [2]:
import numpy as np
List = int(input("Enter size of list:"))
print()
Array1 = list(int(num) 
  for num in input("Enter the list number seperated by space").strip().split())
print("First List:", Array1)
print()
Array2 = list(int(num)
  for num in input("Enter the list number seperated by space").strip().split())
print("Second List:",Array2)
print()
Concatenated_array = np.concatenate((Array1,Array2),axis=0)
print(Concatenated_array)
print()
Concatenated_array.sort()
print("Sorted Array:",Concatenated_array)

Enter size of list:5

Enter the list number seperated by space23 67 29 84 78
First List: [23, 67, 29, 84, 78]

Enter the list number seperated by space34 79 9 24 54
Second List: [34, 79, 9, 24, 54]

[23 67 29 84 78 34 79  9 24 54]

Sorted Array: [ 9 23 24 29 34 54 67 78 79 84]


# Question 3

In [4]:
import numpy as np
arr2D = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('2D Numpy Array')
print(arr2D)
print("\n")
numofRows = np.size(arr2D,0)
print('Number of Rows:', numofRows)
numofColumns = np.size(arr2D,1)
print('Number of Columns:',numofColumns)

2D Numpy Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Number of Rows: 3
Number of Columns: 4


# Question 4

In [5]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print()
print(arr.reshape(5,2))

[ 1  2  3  4  5  6  7  8  9 10]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


# Question 5

In [6]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(np.vstack((x,y)))
print()
print(np.hstack((x,y)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


# Question 6

In [7]:
import numpy as np
arr = np.array([10,10,20,20,20,30,50,60,49,60,49,30])
#unique elements
print(np.unique(arr))
print()
#count unique elements
arr_1 = set(arr)
print(len(arr_1))

[10 20 30 49 50 60]

6
